baseURL = 'https://victoronsoftware.com/'
languageCode = 'en-us'
paginate = 10
title = 'Victor on Software'
theme = "hugo-theme-stack"
enableRobotsTXT = true

[params]
description = "Software engineering, security, and related topics. Currently building security telemetry and MDM at Fleet Device Management."
mainSections = ["posts"]

[params.sidebar]
subtitle = "Software engineering, security, and related topics"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

## Widgets
[[widgets.homepage]]
type = "search"
